# This config file will allow users to change the hyperparameters used in the XGBoost model.

---
data:
  train_path: "data/processed/train.csv"
  val_path: "data/processed/train.csv"
  target: "play_subtype"

model_params:
  # Core XGBoost parameters
  objective: "multi:softmax"
  num_class: 4
  tree_method: "hist"
  eval_metric: "mlogloss"

  # Hyperparameters
  learning rate: 
  max_depth: 
  subsample: 
  colsample_bytree: 
  lambda: 
  alpha: 
  n_estimators: 1000

model_features: 
  - season
  - week
  - qtr
  - down
  - ydstogo
  - yardline_100
  - score_differential
  - def_pass_rate_hist
  - avg_yds_per_play_alwd_hist
  - avg_rush_per_play_alwd_hist

logging: 
  verbose: true 
  log_iteration_interval: 10
...
