# This config file will allow users to change the hyperparameters used in the XGBoost model.

---
data:
  target: "play_subtype"

model_params:
  # Core XGBoost parameters
  objective: "multi:softmax"
  num_class: 4
  tree_method: "hist"
  eval_metric: "mlogloss"

  # Hyperparameters
  tuning:
    enabled: true
    method: randomized
    n_iter: 4
    cv_folds: 3
    n_jobs: 1

  search_space:
    n_estimators: [100, 500] # enter 2 numbers, (low, high) for randint
    max_depth: [2, 3, 4, 5]
    learning_rate: [.01, .05, .1]
    subsample: [0.3, 0.6]
    colsample_bytree: [0.25, 0.5]
    lambda: [1, 2, 3]
    alpha: [1, 2, 3]

  learning_rate: 
  max_depth: 
  subsample: 
  colsample_bytree: 
  lambda: 
  alpha: 
  n_estimators: 1000

model_features: 
  - season
  - week
  - qtr
  - down
  - ydstogo
  - yardline_100
  - score_differential
  - def_pass_rate_rolling
  - avg_yds_pp_alwd_rolling
  - avg_rush_yds_per_rush_alwd_rolling

logging: 
  verbose: true 
  log_iteration_interval: 10
...
